# Basic Settings
title: dario.com • Privacy is our business
description: We optimize privacy compliance, building personal data security into the fabric of your organization, fostering consumer trust, fuelling growth and innovation.
author:
# Language format language_TERRITORY. Default is en_US
lang: en_US
# website logos, images & icons
logo: img/chklst.png
image: img/header.jpg
# urls
url: https://dario.com
english_url: ''
french_url: 'fr'
baseurl: ''
resources_url: 'resources'
services_url: 'services'

# copyright text in footer
copyright: dario.com

# email address
email: contact@dario.com
email_username: contact@dario.com
# email address in privacy policy
email_privacy: privacy@dario.com

# contact telephone number
telephone_number:

# Google Analytics id
google_tracking_id: UA-98131817-2

webmaster_verifications:
  google: jKNeXGKZ4e1CsWLJx1vciAX-AIUBkpglQ_LG5jZfQKc
  bing: AC24F3DF5CA3A5221FB7E01EF2D9AAC4
  alexa:
  yandex:
  baidu:

# Social/SEO
twitter_username:
github_username:
facebook_username:

twitter:
  username:

facebook:
  app_id:
  publisher:
  admins:

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]

# gems
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
